apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name.http }}
  namespace: {{ .Values.namespace }}
data:
  RAILS_ENV: "production"
  RAILS_PORT: "3000"
  RAILS_LOG_TO_STDOUT: "enabled"
  RAILS_SERVE_STATIC_FILES: "enabled"
