apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name.http }}-post-install-job
  namespace: {{ .Values.namespace }}
  labels:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Values.name.http }}-post-install-job
      namespace: {{ .Values.namespace }}
    spec:
      restartPolicy: Never
      containers:
      - name: db-migrations
        image: {{ .Values.postInstallJob.image }}
        command: {{ .Values.postInstallJob.command }}
        args: {{ .Values.postInstallJob.args }}
