apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name.http }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  RAILS_MASTER_KEY: YjEwZmQxZTcyYzQzNTAyN2Y1NWI2NWE0NWE5MDBkMTM=
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJwcm9taXNlcHJlc3RvbiIsInBhc3N3b3JkIjoiaVBAXHUwMDI2WW5MRiVLYkBhMyIsImVtYWlsIjoicHJvbWlzZXByZXN0b25AZ21haWwuY29tIiwiYXV0aCI6ImNISnZiV2x6WlhCeVpYTjBiMjQ2YVZCQUpsbHVURVlsUzJKQVlUTT0ifX19
